#!/bin/sh
#SBATCH -J Al16_test
#SBATCH --nodes 3
#SBATCH --tasks-per-node 16
#SBATCH -t 01:00:00
#SBATCH -p all
#SBATCH -o my_job.%j.out
#SBATCH -e my_job.%j.err

cd ${SLURM_SUBMIT_DIR}
mpirun -n 48 ./PEtot_TDDFT_Intel
